### ISSUE TITLE
Company page

### ISSUE THREAD

**Issue by nazarovctrl** [bandlauz/bandla-frontend#112]
https://api.bandla.uz/swagger-ui/index.html#/Company%20controller/create 

https://api.bandla.uz/swagger-ui/index.html#/Company%20controller/find

shu API ni ishlatgan holda login qilsan userlarga o'zlarini company sini yaratish imkoniyatini qo'shish kerak. Company  nega qo'shish kerak?  Masalan kimdir o'zini biznesini bandla ga ulamoqchi bo'lsa u company yaratishi kerak

1ta user faqat 1ta company yarata oladi. Shuning uchun company page ochilishi bilan avval find API si ishlatish kerak company bor bolsa response da company ma'ulotlari qaytaradiladi aks holda bo'mbo'sh bo'ladi

**Comment by akbarjorayev** [comment]
ok

**Comment by akbarjorayev** [comment]
❤️
