### ISSUE TITLE
Text x size bug 

### ISSUE THREAD

**Issue by nazarovctrl** [bandlauz/bandla-frontend#120]
text shu 2ta qizil chizidan otib ketmasligi kere

![image](https://github.com/bandlauz/bandla-frontend/assets/109890132/5956512e-bd6c-4aff-9072-80f9ef35c5e6)

![image](https://github.com/bandlauz/bandla-frontend/assets/109890132/c4851b93-9f2c-4650-a254-e95947f04ce2)

**Comment by akbarjorayev** [comment]
> text shu 2ta qizil chizidan otib ketmasligi kere
> 
> ![image](https://github.com/bandlauz/bandla-frontend/assets/109890132/5956512e-bd6c-4aff-9072-80f9ef35c5e6)
> 

Telda qanaqa bolishi kereligi ham kordatib ber rasmda
