### ISSUE TITLE
Navbar ni Index.js ga olib otish

### ISSUE THREAD

**Issue by nazarovctrl** [bandlauz/bandla-frontend#69]
Hozir hamma page da alohida <Navbar/> qilib ishlatilgan bunaqa qimaslik kerak.
index.js ichida olib otish kere shunda hamma pageda alohida <Navbar/> db yozish kere bomidi.
Lekin login page da <NavbarSimple/> ishlatish kerak

**Comment by akbarjorayev** [comment]
Hop. Qilinadi.
