### ISSUE TITLE
Link optimization

### ISSUE THREAD

**Issue by nazarovctrl** [bandlauz/bandla-frontend#97]
Uz: Navbar da Footerda ishlatilgan linklarni togrilash kerak. Localhostda run bolgandan link ga bosilsa bandla.uz ga emas localhostdagi osha page ga otishi kerak

Eng:
The links used in the footer in the navbar should be fixed. After running on localhost, if you click on the link, it should go to another page on localhost, not to bandla.uz.

**Comment by nazarovctrl** [comment]
NavbarSimple da qolib ketgan ekan @akbarjorayev

**Comment by akbarjorayev** [comment]
Fixed https://github.com/bandlauz/bandla-frontend/pull/113

**Comment by akbarjorayev** [comment]
> NavbarSimple da qolib ketgan ekan @akbarjorayev

Fixed in #114
